tasks:
    path: /
    controller: App\Controller\TaskController::index
register:
    path: /registro
    controller: App\Controller\UsuarioController::register
login:
    path: /login
    controller: App\Controller\UsuarioController::login
logout:
    path: /logout